
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
#    service:
#      name: webhook-service
#      namespace: system
#      path: /mutate-batch-tutorial-kubebuilder-io-v1-cronjob
     url: https://8867-104-232-234-8.ngrok.io/mutate-batch-tutorial-kubebuilder-io-v1-cronjob
  failurePolicy: Fail
  name: mcronjob.kb.io
  rules:
  - apiGroups:
    - batch.tutorial.kubebuilder.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cronjobs
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: https://8867-104-232-234-8.ngrok.io/mutate-batch-tutorial-kubebuilder-io-v1-cronjob
  failurePolicy: Fail
  name: vcronjob.kb.io
  rules:
  - apiGroups:
    - batch.tutorial.kubebuilder.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cronjobs
  sideEffects: None
